### PR TITLE
fix(replaceEnvVarString.js): Convert BUILD_PIPELINE_INSTANCE_VARS from JSON string to URL query paramaters

### PR DESCRIPTION
**Pull request by laurenty**

### CODE REVIEW

**Comment by illuminateci** [comment]
release 0.2.19 → 0.2.20 [skip ci]
tag to create: v0.2.20
increment detected: PATCH

**Comment by illuminateci** [comment]
release 0.2.19 → 0.2.20 [skip ci]
tag to create: v0.2.20
increment detected: PATCH

**Comment by illuminateci** [comment]
release 0.2.19 → 0.2.20 [skip ci]
tag to create: v0.2.20
increment detected: PATCH

**Review by iesapalad — APPROVED** [review]
looks good

**Pull request merged**
